---
title: "DS 6373 Time Series Project"
author: "Alexandre Jasserme & Jae Chung"
date: "2024-04-04"
output: html_document
---

TODO: ALEX
```{r setup}
knitr::opts_chunk$set(echo = TRUE)

# TO DO: FIX WHAT IS DISPLAYED IN THE FINAL RMD FILE (FOR EXAMPLE, REMOVE WARNING MESSAGES FROM LIBRARY LOADS)

library(tswge)
library(vars)
library(nnfor)
library(GGally)

# Loading the Key Economic Indicators data (downloaded from 
# https://data.texas.gov/dataset/Key-Economic-Indicators/karz-jr5v/about_data)
kei = read.csv("Data/Key_Economic_Indicators_20240401.csv", header = TRUE)

# Checking that data was loaded correctly
head(kei)

# We are interested in the modeling the Existing Single Family Home Price TX 
# (column Q) based on the evolution of the Consumer Price Index TX (column G) 
# and Unemployment TX (column L) from January 2007 (since we have missing data 
# from previous time periods)
cpi = na.omit(kei$Consumer.Price.Index.TX)
unemp = na.omit(kei$Unemployment.TX)
home_price = na.omit(kei$Existing.Single.Family.Home.Price.TX)

# Creating the time series objects 
cpi_ts = ts(data = cpi, start = c(2007,1), frequency = 12)
unemp_ts = ts(data = unemp, start = c(2007,1), frequency = 12)
home_price_ts = ts(data = home_price, start = c(2007,1), frequency = 12)

# Plotting the data
plotts.sample.wge(cpi_ts)
plotts.sample.wge(unemp_ts)
plotts.sample.wge(home_price_ts)

# Creating a data frame:
df = data.frame(cpi, unemp, home_price)

# Looking at the data pairs
ggpairs(df)

# Training and test set for short term forecast (6 months)

# Data Frame
short_term = 6
train_index_short = nrow(df) - short_term
df_train_s = head(df, n=train_index_short)
df_test_s = tail(df, n=short_term)

# Time series
cpi_ts_train_s = ts(data = df_train_s$cpi, start = c(2007,1), frequency = 12)
unemp_ts_train_s = ts(data = df_train_s$unemp, start = c(2007,1), frequency = 12)
home_price_ts_train_s = ts(data = df_train_s$home_price, start = c(2007,1), frequency = 12)

cpi_ts_test_s = ts(data = df_test_s$cpi, start = c(2023,9), frequency = 12)
unemp_ts_test_s = ts(data = df_test_s$unemp, start = c(2023,9), frequency = 12)
home_price_ts_test_s = ts(data = df_test_s$home_price, start = c(2023,9), frequency = 12)

# Training and test set for long term forecast (5 years)

# Data Frame
long_term = 60
train_index_long = nrow(df) - long_term
df_train_l = head(df, n=train_index_long)
df_test_l = tail(df, n=long_term)

# Time series
cpi_ts_train_l = ts(data = df_train_l$cpi, start = c(2007,1), frequency = 12)
unemp_ts_train_l = ts(data = df_train_l$unemp, start = c(2007,1), frequency = 12)
home_price_ts_train_l = ts(data = df_train_l$home_price, start = c(2007,1), frequency = 12)

cpi_ts_test_l = ts(data = df_test_l$cpi, start = c(2019,3), frequency = 12)
unemp_ts_test_l = ts(data = df_test_l$unemp, start = c(2019,3), frequency = 12)
home_price_ts_test_l = ts(data = df_test_l$home_price, start = c(2019,3), frequency = 12)

```

TODO: JAE
```{r}
# 4a. Fitting ARMA / ARIMA / ARUMA / Signal Plus Noise (univariate analysis)
```

TODO: ALEX
```{r}
# 4b. Fitting VAR model
# TO DO: very basic model, need to refine it
VARselect(df, type = "none")
var_fit=VAR(df,p=2,type="none")
var_fit
```

TODO: ALEX
```{r}
# 4c. Fitting Neural Network (mlp) model

# TO DO: very basic model, need to refine it
mlp_fit = mlp(home_price_ts, xreg = data.frame(cpi_ts, unemp_ts))
mlp_fit
```

TODO: JAE
```{r}
# 4d. Fitting Ensemble model using at least two of the above. 
```

Waiting until we have fleshed out the models
```{r}
# 5. Pick a short and long term forecast horizon based on your “problem” from part 3 above and compare all models with the ASE and the rolling window RMSE for both the short and long term forecasts 
# Short term: 6 months
# Long term: 5 years

```

Waiting until we have fleshed out the models
```{r}
# 6. Provide the forecasts and prediction limits (when possible) for both the short and long term forecasts. 
# Waiting until we have fleshed out the models
```